# Generated by Django 5.1.2 on 2024-11-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_created_post_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='shohruh', max_length=250),
        ),
    ]
